### ISSUE TITLE
Failed to activate the browse package

### ISSUE THREAD

**Issue by ghost** [idleberg/atom-browse#7]
[Enter steps to reproduce:]

1. Happens as soon as Atom is opened.

**Atom**: 1.49.0 x64
**Electron**: 5.0.13
**OS**: Pop!_OS 20.04
**Thrown From**: [browse](https://github.com/idleberg/atom-browse) package 3.0.3

### Stack Trace

Failed to activate the browse package

```
At The "path" argument must be of type string. Received type undefined

TypeError [ERR_INVALID_ARG_TYPE] [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:105:11)
    at Object.join (path.js:1037:7)
    at PackageManager.resolvePackagePath (/usr/share/atom/resources/app/static/<embedded>:11:375250)
    at /packages/browse/lib/browse.js:16:27968)
    at Object.t.readManifestSync (/packages/browse/lib/browse.js:16:28386)
    at /packages/browse/lib/browse.js:16:28540
    at /packages/browse/lib/browse.js:16:1530)
    at /packages/browse/lib/browse.js:16:28463)
    at /packages/browse/lib/browse.js:19:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:147498)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:151046)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:14:16)
    at customRequire (/usr/share/atom/resources/app/static/<embedded>:1:695413)
    at Package.requireMainModule (/usr/share/atom/resources/app/static/<embedded>:11:3201906)
    at Package.activateNow (/usr/share/atom/resources/app/static/<embedded>:11:3189890)
    at /usr/share/atom/resources/app/static/<embedded>:14:2607
    at Function.simpleDispatch (/usr/share/atom/resources/app/static/<embedded>:11:1201500)
    at Emitter.emit (/usr/share/atom/resources/app/static/<embedded>:11:1202941)
    at PackageManager.triggerActivationHook (/usr/share/atom/resources/app/static/<embedded>:11:383691)
    at AtomEnvironment.updateProcessEnvAndTriggerHooks (/usr/share/atom/resources/app/static/<embedded>:1:720378)
    at async Promise.all (index 2)
    at AtomEnvironment.startEditorWindow (/usr/share/atom/resources/app/static/<embedded>:1:718063)
```

### Commands

```
```

### Non-Core Packages

```
atom-ide-ui 0.13.0 
atom-wrap-in-tag 0.6.0 
auto-update-plus 0.5.8 
browse 3.0.3 
build 0.70.0 
busy-signal 2.0.1 
ctrl-dir-scroll 0.2.5 
Hydrogen 2.14.5 
ide-python 1.5.0 
kite 0.191.0 
minimap 4.29.9 
multi-cursor 3.0.0 
python-debugger 0.2.0 
satisfy-dependencies 0.4.2 
script 3.26.0 
set-syntax 0.4.0 
sublime 0.5.0 
sublime-block-comment 0.5.1 
Sublime-Style-Column-Selection 1.7.5 
sublime-word-navigation 0.2.1 
tag 0.5.0 
text-manipulation 0.6.0 
```

**Comment by idleberg** [comment]
Thanks for reporting. This was hopefully fixed in v3.1.0!

**Comment by idleberg** [comment]
Even though it's fixed now, may I ask how you installed the package?

**Comment by ghost** [comment]
I didn't install the package by itself. It must have come bundled with
other packages that I installed, perhaps as a dependency.

I used the built-in atom package installer. Sorry, I hope this helps.
